SoftDevIII/isc-03-hermes

- .github/workflows/check-push.yml
- README.md
> chore: improve readme

- apps/client/package.json
- apps/client/src/app/App.tsx
- apps/client/src/app/map/Map.tsx
- apps/client/src/app/map/MapProps.ts
- apps/client/src/vite-env.d.ts
- package-lock.json
> feat: display the map

- apps/client/src/app/pages/map/components/marker/Marker.tsx
- apps/client/src/app/pages/map/components/marker/components/CoordinatesDisplay.tsx
- apps/client/src/app/pages/map/components/marker/components/DropdownMenu.tsx
Feature: Improve UI design and also refactor the code for marker options
> feat: improve menu drop down ui

- apps/client/src/app/globals/types.d.tsx
- apps/client/src/app/pages/map/MapPage.tsx
- apps/client/src/app/pages/map/components/actual-location/ActualLocation.tsx
- apps/client/src/app/pages/map/hooks/useActualLocation.tsx
- apps/client/src/app/pages/map/shared-ui-components/ActualLocationButton.tsx
> feat: implement redirect to user actual location

- apps/client/src/app/pages/map/components/actual-location/ActualLocation.tsx
- apps/client/src/app/pages/map/components/zoom/Zoom.tsx
- apps/client/src/app/pages/map/components/zoom/ZoomLevel.tsx
- apps/client/src/app/pages/map/hooks/useLevelZoom.tsx
- [x ] ✨ New feature (non-breaking change which adds functionality)
> feat: display zoom level

- apps/client/src/app/globals/types.d.tsx
- apps/client/src/app/pages/map/components/actual-location/ActualLocation.tsx
- apps/client/src/app/pages/map/hooks/useActualLocation.tsx
- apps/client/src/app/pages/map/shared-ui-components/ActualLocationButton.tsx
- improve the functionality of obtaining the user's location
- make it only ask for permission for the location once until the process is finished
- add a tooltip to ActualLocation for better UX
- add the ability to support scenarios such as: location timeout, geolocation permissions and if you have geolocation enabled
- make the button to enable or disable depends of the situation
> feat: improve user location

- apps/client/src/app/globals/types.d.tsx
- apps/client/src/app/pages/home/HomePage.tsx
- apps/client/src/app/pages/home/components/header/Header.tsx
- apps/client/src/app/pages/home/components/header/components/ReferenceButton.tsx
- apps/client/src/app/pages/home/components/sections/AboutSection.tsx
- apps/client/src/app/pages/home/components/sections/FunctionsSection.tsx
- apps/client/src/app/pages/home/components/sections/HomeSection.tsx
- apps/client/src/app/pages/map/styles/scroll-bar.css
This is an integration of the footer and header components with the home page
> feat: integrate footer and header with home

- apps/client/src/app/api/data/places-details.json
Update information of public places to display to have a better user experience when user looks for a place.
> fix: update api information for details of public places

- apps/api/src/app.module.ts
- apps/api/src/customer/customer.controller.ts
- apps/api/src/customer/customer.module.ts
- apps/api/src/customer/customer.service.ts
- apps/api/src/customer/custumer.entity.ts
- apps/api/src/customer/dto/create-customer.dto.ts
- apps/client/src/app/pages/sign-up/SignUpPage.tsx
- apps/db/sql/init.sql
- apps/db/sql/query.sql
> feat: implement user addition to the database

- apps/client/src/app/api/WeatherAPI.ts
- apps/client/src/app/globals/types.d.tsx
- apps/client/src/app/pages/map/components/left-control/LeftControl.tsx
- apps/client/src/app/pages/map/components/search-bar/services/SearchBarService.ts
- apps/client/src/vite-env.d.ts
> feat: implement fetch apis

- apps/api/src/app.module.ts
- apps/api/src/customer/customer.controller.ts
- apps/api/src/customer/custumer.entity.ts
- apps/client/src/app/pages/login/LoginPage.tsx
- apps/db/sql/init.sql
- apps/db/sql/query.sql
> feat: implement user credential verificacion with login UI

- apps/client/src/app/App.tsx
- apps/client/src/app/globals/types.d.tsx
- apps/client/src/app/pages/disaster/DisasterPage.tsx
- apps/client/src/app/pages/disaster/Service/SearchDisasterData.tsx
- apps/client/src/app/shared-components/InputDisaster.tsx
- apps/client/src/app/shared-components/InputLocation.tsx
> feat: functional disaster page

- apps/client/src/app/globals/types.d.tsx
- apps/client/src/app/pages/map/components/search-bar/components/context-menu/ContextMenu.tsx
- apps/client/src/app/pages/map/components/search-bar/components/context-menu/components/Menu.tsx
- apps/client/src/app/pages/map/components/search-bar/components/context-menu/components/place/CloseButtonPlace.tsx
- apps/client/src/app/pages/map/components/search-bar/components/context-menu/components/place/CommonPlace.tsx
- apps/client/src/app/pages/map/components/search-bar/components/context-menu/components/place/UncommonPlace.tsx
- apps/client/src/app/pages/map/components/search-bar/components/context-menu/components/share-location/ShareLink.tsx
- apps/client/src/app/pages/map/components/search-bar/components/context-menu/components/share-location/components/ShareButton.tsx
- apps/client/src/app/pages/map/components/search-bar/components/context-menu/hooks/useHandleClick.tsx
- apps/client/src/app/pages/map/components/search-bar/hooks/useSearchInput.tsx
- apps/client/src/app/pages/map/components/search-bar/services/SearchBarService.ts
> feat: implement place pop up

- apps/client/src/app/globals/types.d.tsx
- apps/client/src/app/pages/disaster/DisasterPage.tsx
- apps/client/src/app/pages/disaster/hooks/useSearchDisasterInput.tsx
> fix: disaster page eslint problem

- apps/client/src/app/App.tsx
- apps/client/src/app/globals/types.d.tsx
- apps/client/src/app/pages/map/MapPage.tsx
- apps/client/src/app/pages/map/components/search-bar/SearchBar.tsx
- apps/client/src/app/pages/map/components/search-bar/components/context-menu/components/share-location/ShareLink.tsx
> feat: implement redirect

- apps/api/src/app.module.ts
- apps/api/src/regex/dto/create-regex.dto.ts
- apps/api/src/regex/regex.controller.ts
- apps/api/src/regex/regex.entity.ts
- apps/api/src/regex/regex.enum.ts
- apps/api/src/regex/regex.module.ts
- apps/api/src/regex/regex.service.ts
- apps/api/src/regex/test/regex.service.spec.ts
> feat: implemente regex account validation

- apps/api/src/customer/customer.controller.ts
- apps/api/src/customer/customer.service.ts
- apps/api/src/customer/custumer.entity.ts
- apps/db/sql/init.sql
- apps/db/sql/query.sql
> fix: correct log in and sign up funcionality

- apps/client/src/app/pages/home/components/header/Header.tsx
- apps/client/src/app/pages/map/components/search-bar/components/menu/components/MenuList.tsx
- apps/client/src/app/pages/map/components/search-bar/components/menu/components/MenuUser.tsx
- apps/client/src/app/pages/map/components/search-bar/components/menu/hooks/useMenuActions.tsx
> feat: add redirection to sidebar and header

- apps/client/src/app/App.tsx
- apps/client/src/app/pages/disaster/DisasterPage.tsx
- apps/client/src/app/pages/home/components/header/Header.tsx
- apps/client/src/app/pages/home/components/header/components/IsNotLoggedInView.tsx
> feat: integration with all pages

- apps/client/src/app/pages/sign-up/SignUpPage.tsx
> fix: solve problems with sign up button

- apps/client/src/app/App.tsx
- apps/client/src/app/globals/types.d.tsx
- apps/client/src/app/pages/disaster/DisasterPage.tsx
- apps/client/src/app/pages/disaster/Service/SearchDisasterData.tsx
- apps/client/src/app/pages/disaster/hooks/useSearchDisasterInput.tsx
- apps/client/src/app/pages/login/LoginPage.tsx
- apps/client/src/app/pages/map/components/search-bar/components/menu/components/MenuList.tsx
- apps/client/src/app/pages/map/components/search-bar/components/menu/components/MenuOptionButton.tsx
- apps/client/src/app/pages/map/components/search-bar/components/menu/hooks/useMenuActions.tsx
- apps/client/src/app/pages/sign-up/SignUpPage.tsx
- apps/client/src/app/shared-components/GoBackButton.tsx
- apps/client/src/app/shared-components/SubmitButton.tsx
> fix: Disaster Page Bugs

- apps/client/src/app/pages/home/HomePage.tsx
home page view being fixed
Closes #86, Closes #87
> fix: home page bug

- apps/client/src/app/pages/map/components/route/PopUpForRouteInformation.tsx
- apps/client/src/app/pages/map/components/route/hooks/useGetRoute.tsx
> fix: current location route

- apps/client/src/app/globals/types.d.tsx
- apps/client/src/app/pages/home/components/header/components/MenuSideBar.tsx
- apps/client/src/app/pages/home/components/header/components/ReferenceButton.tsx
- apps/client/src/app/pages/home/components/header/hooks/useMenuSideBarRef.tsx
> fix: go map button headbar

- apps/client/src/app/pages/login/LoginPage.tsx
> fix: solve error message on login page
